const mentors = [
  {
    loginid: "99whatever",
    userid: 1,
    firstname: "Fred",
    surname: "Jones",
    jobtitle: "UX.UI Designer",
    company: "ASOS",
    email: "fred@fredjpnes.com",
    biography: "Fred was born a long time ago.",
    socials: {
      name: "Github",
      userName: "fred@github",
    },
    location: "London",
    photourl:
      "https://d3vlf99qeg6bpx.cloudfront.net/content/uploads/2021/10/14174415/manchester-united-midfielder-fred-2021.jpg",
    tagline: "I am cool",
    skills: ["javascript", "postgres", "cooking"],
    relationships: {},
  },
  {
    loginid: "17whatever",
    userid: 2,
    firstname: "Sally",
    surname: "Davies",
    jobtitle: "Chief Of Delivery",
    company: "Argos",
    email: "sally@hotmail.com",
    biography: "Sally plays darts.",
    socials: {
      name: "Github",
      userName: "sally@github",
    },
    location: "Edinburgh",
    photourl: "https://m.media-amazon.com/images/I/61h+zQna+tL._AC_SX425_.jpg",
    tagline: "Sally be good",
    skills: ["javascript", "postgres", "database"],
    relationships: {},
  },
  {
    loginid: "12whatever",
    userid: 3,
    firstname: "Bob",
    surname: "Bobbits",
    jobtitle: "The Chief",
    company: "Megacorp",
    email: "bob@bobbits.com",
    biography:
      "Bob first started coding in the original dot.com boom of 1952, and has led the field in Bobness for nearly seven decades now - continually pushing the boundaries of bobness, and taking in multiple shifts in direction.  He has two cats and lives in the Algarve.",
    socials: {
      linkedin: "bob@linkedin",
    },
    location: "Scarborough",
    photourl:
      "https://i.pinimg.com/originals/e7/c1/67/e7c167c2372de5eaff3912377d6d88d2.jpg",
    tagline: "Best Bob in town...",
    skills: ["frontend", "ux-ui"],
    relationships: {},
  },
  {
    loginid: "zDUYZqhczLdj0rZTZkcvo7D7o192",
    userid: 72,
    firstname: "Jeff ",
    surname: "Jeffreys",
    jobtitle: "Dolphin Trainer",
    company: "Dolphins Inc",
    email: "jeff@jeff.com",
    biography:
      "sdhfgfkhlhgfjkgfkg tyykjhgliu ftjykuyuyyftiyk fjtyfkuygulh ytfuylgu jydytfky l tfyl.  ryjkgju djhf tdrf Afkjg djthf .",
    socials: {
      twitter: "@dolphinjeff",
    },
    location: "Sweden",
    photourl: "https://i1.sndcdn.com/avatars-000118363108-3sw4bk-t240x240.jpg",
    tagline: "Dolphin expert",
    skills: ["frontend", "ux-ui", "fullstack"],
    relationships: null,
  },
  {
    loginid: "J0jlLzFE3iSbaK5OPmvu1GALBUh2",
    userid: 87,
    firstname: "Bob",
    surname: "Jeff",
    jobtitle: "Chef",
    company: "Monsters Inc",
    email: "bob@jeff.com",
    biography: "Bob was a chef at the best restaurant in the world.",
    socials: {
      linkedin: "@cookingatLinkedIn",
    },
    location: "Rosklide",
    photourl:
      "https://64.media.tumblr.com/3e7674aae90c5978619425610e7143bc/3944b0b0a25bc7d4-4f/s1280x1920/853f21d96fadf2c4b49125b184b82d1fd5a71b8c.jpg",
    tagline: "Cooking it up",
    skills: ["frontend", "fullstack", "backend", "ux-ui"],
    relationships: null,
  },
  {
    loginid: "71Pj0h4QqxUQMdeBqP03MQ8XtfK2",
    userid: 4,
    firstname: "Novel",
    surname: "Alam",
    jobtitle: "Software Developer",
    company: "Soc",
    email: "NovelAlam@hotmail.com",
    biography: "meh",
    socials: {
      github: "NovelAlam",
    },
    location: "LONDON",
    photourl: null,
    tagline: "Hey",
    skills: ["frontend", "backend", "fullstack"],
    relationships: null,
  },
  {
    loginid: "cLet1yZQR2V0Yyp62hhupHJ8shF3",
    userid: 104,
    firstname: "goy",
    surname: "miah",
    jobtitle: "dev",
    company: "soc",
    email: "goyas@gmail",
    biography: "to tired to type",
    socials: {
      "": "dont have on",
    },
    location: "midlands",
    photourl: "comming soon",
    tagline: "student of life",
    skills: ["backend"],
    relationships: null,
  },
  {
    loginid: "weYTOsGpnIc0SwFrfgihWFLVDAq1",
    userid: 80,
    firstname: "Qwert ",
    surname: "Qwert",
    jobtitle: "Qwerrist",
    company: "Qwert iNc",
    email: "qwert@qwert.com",
    biography:
      "fgfchgkjlkjgjgkchvjhhj  kgjhhllkgfhjgfk. A jhghk  hfgjth  to ghfgfj fk fgjk   fytfglul.",
    socials: {
      "": "",
    },
    location: "Qwert city",
    photourl: null,
    tagline: "QWERT!",
    skills: [],
    relationships: null,
  },
  {
    loginid: "33KU0QZbkHWda78VRnWPVSdeT0B3",
    userid: 119,
    firstname: null,
    surname: null,
    jobtitle: null,
    company: null,
    email: null,
    biography: null,
    socials: null,
    location: null,
    photourl: null,
    tagline: null,
    skills: null,
    relationships: null,
  },
  {
    loginid: "9cIfIYnUWgWQ2eMjI6XSYvBoYHJ2",
    userid: 9,
    firstname: "Asani",
    surname: "xx",
    jobtitle: "sdgdfn",
    company: "gndgn",
    email: "sdgsd@safakgf.com",
    biography: "sdhdf dfhd fkykgj  rgsg x dg  drrgd",
    socials: {
      twitter: "@asani",
    },
    location: "essex",
    photourl: null,
    tagline: "dh sg rgs erg ykg e",
    skills: ["frontend", "backend"],
    relationships: null,
  },
  {
    loginid: "gnSKBFor79OX9fiXPnMvvrwyMje2",
    userid: 127,
    firstname: "",
    surname: "",
    jobtitle: "",
    company: "",
    email: "",
    biography: "",
    socials: {
      "": "",
    },
    location: "",
    photourl: "",
    tagline: "",
    skills: [],
    relationships: null,
  },
  {
    loginid: "hJAvwClURqXX0aiqsKsIlXqNa0R2",
    userid: 8,
    firstname: "Simon",
    surname: "Prato",
    jobtitle: "adsasdd",
    company: "as",
    email: "sad@hjasdjhas",
    biography:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequuntur, blanditiis ex suscipit, quaerat iusto veritatis cupiditate asperiores corrupti labore modi optio. Dolorem quibusdam ex vitae sapiente fugiat. Quis, blanditiis reiciendis.",
    socials: {
      github: "dasdasdgithu",
    },
    location: "adsdsad",
    photourl: null,
    tagline: "adssd",
    skills: [],
    relationships: null,
  },
  {
    loginid: "w2YJ5qHgMZaQrDLO0BSjJ5H7xsj2",
    userid: 122,
    firstname: "Carlo",
    surname: "Montoya",
    jobtitle: "Striker",
    company: "FC Barcelona",
    email: "carlo@montoya.com",
    biography:
      "Carlos Fernando Navarro Montoya (born 26 February 1966) is a retired footballer who played as a goalkeeper. Born in Colombia, Navarro Montoya represented the Colombia national team three times, and gained Argentine citizenship later in his career.  During a professional career which spanned 25 years, he represented teams in Argentina, Colombia, Spain, Chile, Brazil and Uruguay, appearing for 15 clubs (mainly Boca Juniors) and totalling more than 800 games across all competitions.",
    socials: {
      twitter: "@carlomontoya",
    },
    location: "Barcelona",
    photourl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Navarro_montoya_boca.jpg/300px-Navarro_montoya_boca.jpg",
    tagline: "Safest hands in Barcelona!",
    skills: ["backend"],
    relationships: null,
  },
  {
    loginid: "AuTqPEVjr8bfxkJ8HdGoVlAaLVE2",
    userid: 5,
    firstname: "Janet",
    surname: "Jones",
    jobtitle: "CEO",
    company: "Amazon",
    email: "janet@jones.com",
    biography:
      "Janet Damita Jo Jackson (born May 16, 1966) is an American singer, songwriter, actress, and dancer. She is noted for her innovative, socially conscious and sexually provocative records, as well as elaborate stage shows. Her sound and choreography became a catalyst in the growth of MTV, enabling her to rise to prominence while breaking gender and racial barriers in the process. Lyrical content which focused on social issues set her reputation as a role model for youth.  The tenth and youngest child of the Jackson family, she began her career with the variety television series The Jacksons in 1976 and went on to appear in other television shows throughout the 1970s and early 1980s, including Good Times, Diff'rent Strokes, and Fame. After signing a recording contract with A&M Records in 1982, she became a pop icon following the release of her third and fourth studio albums Control (1986) and Rhythm Nation 1814 (1989). Her collaborations with record producers Jimmy Jam and Terry Lewis incorporated elements of rhythm and blues, funk, disco, rap, and industrial beats, which led to crossover success in popular music.",
    socials: {
      twitter: "@janet",
    },
    location: "Colorado",
    photourl:
      "https://www.billboard.com/wp-content/uploads/2020/05/Janet-Jackson-1990-a-billboard-1548-1589489884.jpg?w=1024",
    tagline: "Yep!",
    skills: ["frontend"],
    relationships: null,
  },
];

export default mentors;
